on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: compile
        run: mvn clean compile test-compile

      - name: unit-tests
        run: mvn surefire:test

      - name: integration-tests
        run: mvn failsafe:integration-test failsafe:verify

      # Deploy RELEASE every night? To discuss with the whole team...

#      - name: sonarqube
#        run: mvn sonar:sonar -Dsonar.host.url=http://sonarqube.avidesmedia/
