name: pull_request

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/checkout@v1

      - name: compile
        run: mvn clean compile test-compile

      - name: unit-tests
        run: mvn surefire:test

      - name: integration-tests
        run: mvn failsafe:integration-test failsafe:verify

      - name: sonarqube
        run: cat ${GITHUB_EVENT_PATH}

      #      - name: sonarqube
      #        run: |
      #          mvn sonar:sonar \
      #            -Dsonar.analysis.preview \
      #            -Dsonar.issuesReport.console.enable=true \
      #            -Dsonar.projectKey=springboot-testcontainer_springboot-testcontainer-common \
      #            -Dsonar.organization=springboot-testcontainer \
      #            -Dsonar.host.url=https://sonarcloud.io \
      #            -Dsonar.login=f463548288e26f4df00c3066ee432161caf766f8

      - name: pom-analyse
        run: mvn enforcer:enforce
