name: release

on:
  push:
    branches:
      - LIBS-721

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      OSSRH_USERNAME: ${{ secrets.OS_OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OS_OSSRH_PASSWORD }}

    steps:
      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD

      - name: setup-gpg
        env:
          GPG_PRIVATE_KEY: ${{ secrets.OS_GPG_PRIVATE_KEY }}
        run: echo ${GPG_PRIVATE_KEY} | base64 --decode | gpg --batch --import

      - name: checkout
        uses: actions/checkout@v2

      - name: caching
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: deploy
        env:
          GPG_PASSPHRASE: ${{ secrets.OS_GPG_PASSPHRASE }}
        run: mvn deploy -Dgpg.passphrase=${GPG_PASSPHRASE}

      - name: sonar-analyse
        env:
          SONAR_HOST: ${{ secrets.OS_SONAR_HOST }}
          SONAR_TOKEN: ${{ secrets.OS_SONAR_TOKEN }}
        run: |
          export SONAR_ORGANIZATION=$(echo ${GITHUB_REPOSITORY} | cut -d / -f 1)
          mvn sonar:sonar \
            -Dsonar.host.url=${SONAR_HOST} \
            -Dsonar.login=${SONAR_TOKEN} \
            -Dsonar.organization=${SONAR_ORGANIZATION} \
            -Dsonar.projectKey=${GITHUB_REPOSITORY//\//_} \
            -Dsonar.java.binaries=./target/classes
