on:
  push:
    branches:
      - ITADMIN-2021

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v1

      - name: setup-release
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: |
          mkdir ~/.m2
          echo "<settings><servers><server><id>github</id><username>${GITHUB_USERNAME}</username><password>${GITHUB_PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: release
        run: mvn clean deploy -Dmaven.test.skip=true

#      - name: sonarqube
#        run: mvn sonar:sonar -Dsonar.host.url=http://sonarqube.avidesmedia/

