name: review

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: checkout
        uses: actions/checkout@v1

      - name: caching
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: compile
        run: mvn clean compile test-compile

      - name: unit-tests
        run: mvn surefire:test

      - name: integration-tests
        run: mvn failsafe:integration-test failsafe:verify

      - name: setup-sonarqube
        uses: warchant/setup-sonar-scanner@v1
      - name: sonarqube
        env:
          # to get access to secrets.SONAR_TOKEN, provide GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=springboot-testcontainer
          -Dsonar.host.url=https://sonarcloud.io/
          -Dsonar.projectKey=springboot-testcontainer_springboot-testcontainer-common

      - name: pom-analyse
        run: mvn enforcer:enforce
