name: review_intern_sq

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: checkout
        uses: actions/checkout@v1

      - name: caching
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: compile
        run: mvn clean compile test-compile

      - name: unit-tests
        run: mvn surefire:test

      - name: integration-tests
        run: mvn failsafe:integration-test failsafe:verify

      - name: sonar-analyse
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.analysis.mode=preview \
            -Dsonar.host.url=http://sonarqube.avidesmedia.de/ \
            -Dsonar.branch.name=${GITHUB_REF} \
            -Dsonar.github.oauth=${GITHUB_TOKEN} \
            -Dsonar.github.repository=${GITHUB_REPOSITORY} \
            -Dsonar.github.pullRequest=19 \
            -Dsonar.java.binaries=./target/classes

      - name: pom-analyse
        run: mvn enforcer:enforce
